language: node_js
git:
        depth: 999999
node_js:
        - "8"
before_install:
        - mkdir gh-pages
        - git clone https://github.com/aleen42/PersonalWiki.git -b gh-pages gh-pages
before_deploy:
        - npm run gitbook:install
        - npm run gitbook:build
        - rm deployed* -f
deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
                branch: master
        local_dir: ./gh-pages/
        name: aleen42
        email: aleen42@vip.qq.com
